# Generated by Django 4.2.2 on 2023-06-09 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                ("documento", models.IntegerField(primary_key=True, serialize=False)),
                ("tipo_documento", models.CharField(max_length=20)),
                ("nombre", models.CharField(max_length=100)),
                ("apellido", models.CharField(max_length=100)),
                ("direccion", models.CharField(max_length=200)),
                ("telefono", models.CharField(max_length=20)),
                ("fecha_nacimiento", models.DateField()),
                ("imagen_perfil", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("categoria", models.CharField(max_length=100)),
                ("marca", models.CharField(max_length=100)),
                (
                    "valor_unitario",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("unidades_stock", models.IntegerField()),
                ("descripcion", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Proveedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nit", models.CharField(max_length=20)),
                ("nombre", models.CharField(max_length=100)),
                ("ciudad", models.CharField(max_length=100)),
                ("correo", models.CharField(max_length=100)),
                ("numero_contacto", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Rol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_rol", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_usuario", models.CharField(max_length=100)),
                ("contrasena", models.CharField(max_length=100)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tasks.cliente"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Usuario_Rol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tasks.rol"
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tasks.usuario"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Proveedor_Producto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tasks.producto"
                    ),
                ),
                (
                    "proveedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tasks.proveedor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Cliente_Producto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tasks.cliente"
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tasks.producto"
                    ),
                ),
            ],
        ),
    ]
