# Generated by Django 4.2.2 on 2023-06-10 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_rol_usuarios_alter_usuario_cliente_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaccion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.IntegerField()),
                ("fecha_compra", models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name="proveedor_producto",
            name="producto",
        ),
        migrations.RemoveField(
            model_name="proveedor_producto",
            name="proveedor",
        ),
        migrations.RemoveField(
            model_name="usuario_rol",
            name="rol",
        ),
        migrations.RemoveField(
            model_name="usuario_rol",
            name="usuario",
        ),
        migrations.RemoveField(
            model_name="rol",
            name="usuarios",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="cliente",
        ),
        migrations.AddField(
            model_name="cliente",
            name="usuario",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="tasks.usuario",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="producto",
            name="proveedor",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="tasks.proveedor",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="usuario",
            name="rol",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="tasks.rol"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="cliente",
            name="documento",
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name="Cliente_Producto",
        ),
        migrations.DeleteModel(
            name="Proveedor_Producto",
        ),
        migrations.DeleteModel(
            name="Usuario_Rol",
        ),
        migrations.AddField(
            model_name="transaccion",
            name="cliente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tasks.cliente"
            ),
        ),
        migrations.AddField(
            model_name="transaccion",
            name="producto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tasks.producto"
            ),
        ),
    ]
