# Generated by Django 4.2.2 on 2023-06-10 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_transaccion_remove_proveedor_producto_producto_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cliente",
            old_name="usuario",
            new_name="id_usuario",
        ),
    ]
