# Generated by Django 4.2.2 on 2023-06-10 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0004_rename_usuario_cliente_id_usuario"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usuario",
            name="rol",
        ),
        migrations.AddField(
            model_name="usuario",
            name="roles",
            field=models.ManyToManyField(related_name="usuarios", to="tasks.rol"),
        ),
    ]
