# Generated by Django 4.2.2 on 2023-06-10 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0005_remove_usuario_rol_usuario_roles"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usuario",
            old_name="roles",
            new_name="rol_id",
        ),
    ]
