# Generated by Django 4.2.2 on 2023-06-10 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0006_rename_roles_usuario_rol_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="id_usuario",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tasks.usuario",
            ),
        ),
    ]
